/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entornos.git2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testAgregarPlato() {
        Menu menu = new Menu();
        menu.agregarPlato("Paella", 15.0);
        assertEquals(15.0, menu.getPrecio("Paella"));
    }

    @Test
    public void testEliminarPlato() {
        Menu menu = new Menu();
        menu.agregarPlato("Paella", 15.0);
        menu.eliminarPlato("Paella");
        assertNull(menu.getPrecio("Paella"));
    }

    @Test
    public void testListarMenu() {
        Menu menu = new Menu();
        menu.agregarPlato("Paella", 15.0);
        menu.listarMenu();
    }

    @Test
    public void testAgregarPlatoComanda() {
        Menu menu = new Menu();
        menu.agregarPlato("Paella", 15.0);
        Comanda comanda = new Comanda(menu);
        comanda.agregarPlatoComanda("Paella");
    }

    @Test
    public void testCalcularTotalComanda() {
        Menu menu = new Menu();
        menu.agregarPlato("Paella", 15.0);
        Comanda comanda = new Comanda(menu);
        comanda.agregarPlatoComanda("Paella");
        assertEquals(15.0, comanda.calcularTotalComanda());
    }

    @Test
    public void testMostrarComanda() {
        Menu menu = new Menu();
        menu.agregarPlato("Paella", 15.0);
        Comanda comanda = new Comanda(menu);
        comanda.agregarPlatoComanda("Paella");
        comanda.mostrarComanda();
    }

}
