/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entornos.git2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @test
    // void gestionarMenu() {
    // App classUnderTest = new App();
    // assertEquals(classUnderTest, classUnderTest);
    // assertEquals(classUnderTest, classUnderTest);
    // assertEquals(classUnderTest, classUnderTest);
    // }

    // @test
    // void gestionarComandas() {
    // App classUnderTest = new App();
    // assertEquals(classUnderTest, classUnderTest);
    // assertEquals(classUnderTest, classUnderTest);
    // assertEquals(classUnderTest, classUnderTest);
    // }
}
